apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
      - name: my-echo-server-container
        image: sawyerkent.jfrog.io/docker/my-echo-server:1.0.0
        ports:
        - containerPort: 8080
